### ISSUE TITLE
Add background service for processing uploaded content

### ISSUE THREAD

**Issue by NiloCK** [NiloCK/vue-skuilder#57]
A server-side service is needed for processing user-uploaded content. Built into the express server?

Basic flow:

- Observe the `/changes` feed of the cardData database (see [couch docs](https://docs.couchdb.org/en/stable/api/database/changes.html), [couch - the definitive guide](http://guide.couchdb.org/draft/notifications.html))
- On file upload:
  - do some processing
  - replace the raw input with the processed input

Cases:

- Audio / Video: normalize all audio. (FFMPEG?)
- Images: Create a variety of resizes for different form-factors (imagemagik?)

**Comment by NiloCK** [comment]
For audio normalization:

- ffmpeg -i `input` -af "adelay=10000|10000" `enlarged`
  - Pads the audio with ten seconds of silence at the beginning. Necessary because of [this bug](https://github.com/slhck/ffmpeg-normalize/issues/87)
- ffmpeg -i `enlarged` -af loudnorm=I=-16:TP=-1.5:LRA=11:print_format=json -f null -
  - Gets loudness data from the file
- ffmpeg -i `enlarged` -af loudnorm=I=-16:TP=-1.5:LRA=11:measured_I=-XXX:measured_LRA=XXX:measured_TP=-XXX:measured_thresh=-XXX:offset=0.58:linear=true:print_format=summary -ar 48k `paddedNormalized`
  - Feeds the loudness data back into the normalization alg for better results
- ffmpeg -i `paddedNormalized` -ss 00:00:10.000 -acodec copy `normalized`
  - Removes the 10 seconds of silence

**Comment by NiloCK** [comment]
Next steps:

- [ ] Change `normalize()` function to take a js blob object (or whatever Nano types the attachment as)
- [ ] Add hooks to listen to `_changes` stream of `skuilder` database, dispatch to correct fcns based on MIME types, and update docs post-processing

**Comment by NiloCK** [comment]
Next:

[ ] - Refactor: audio functions to their own file
[ ] - Checking a CouchDB doc for the current `seq` - instead of `"now"`, so that docs uploaded during downtime of the postProcessor don't get missed
[ ] - Check if losing the `since` parameter causes processing of all data in the db
[ ] - See about droplet deployment

**Comment by NiloCK** [comment]
This can move to the back-burner for now. Necessary functionality for personal use is in place. `seq` tracking and deployment automation can wait until 'production'.

**Comment by NiloCK** [comment]
Note: for server-side audio-format conversion:

ffmpeg -i filenameee.m4a -acodec libmp3lame -ab 256k output.mp3

**Comment by MrityunjoyS** [comment]
Hi, I'm trying to use below code -->

> * ffmpeg -i `input` -af "adelay=10000|10000" `enlarged`

But getting below error :-

> 
> [NULL @ 0x5605bb648540] Unable to find a suitable output format for 'enlarged'
> enlarged: Invalid argument

What am I missing here? Please suggest. 
Thanks in advance.
